PickAndMixECommerce/Controllers/BasketItemsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using PickAndMixECommerce.Data.Services;
using PickAndMixECommerce.Models;

namespace PickAndMixECommerce.Controllers
{
    public class BasketItemsController : Controller
    {
        private readonly IBasketItemsService _basketItemsService;
        private readonly ISweetsService _sweetsService;

        public BasketItemsController(IBasketItemsService basketItemsService,ISweetsService sweetsService)
        {
            _basketItemsService = basketItemsService;
            _sweetsService = sweetsService;
        }
        public async Task<IActionResult> Index()
        {
            var basketItemsData = await _basketItemsService.GetBasketItemsAsync();
            return View(basketItemsData);
        }
        public  async Task<IActionResult> AddItem(int id)
        {
            var item = await _sweetsService.GetByIdAsync(id);
            if (item != null) {
            
            _basketItemsService.Add(item);
            }
            return RedirectToAction("Index","Sweets");
        }
    }
}

PickAndMixECommerce/Controllers/SweetsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PickAndMixECommerce.Data;
using PickAndMixECommerce.Data.Services;
using PickAndMixECommerce.Models;

namespace PickAndMixECommerce.Controllers
{
    public class SweetsController : Controller
    {
        private readonly ISweetsService _service;

        public SweetsController(ISweetsService service)
        {
            _service = service;
        }
        public async Task<IActionResult> Index(string sortOrder, string searchString)
        {
            ViewData["CurrentFilter"] = searchString;
            var sweetsData = await _service.GetAllAsync(sortOrder, searchString);
            return View(sweetsData);
        }
        public async Task<IActionResult> Details(int id)
        {
            var sweetDetails = await _service.GetByIdAsync(id);
            if(sweetDetails == null) { return View("NotFound"); }
            return View(sweetDetails);
        }
        public IActionResult Create() {
            return View();
        }
        [HttpPost]
        public IActionResult Create([Bind("ImageUrl,SweetName,PriceInPence,StockInGrams")] Sweet sweet)
        {
            //if (!ModelState.IsValid)
            //{
            //    return View(sweet);
            //}
            _service.Add(sweet);
            return RedirectToAction(nameof(Index));
        }
    }
}

PickAndMixECommerce/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PickAndMix</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PickAndMixECommerce.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="bi bi-list"></i> Menu
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-controller="Sweets" asp-action="Index"><i class="bi bi-house"></i> Home</a>
                                <a class="dropdown-item" asp-controller="BasketItems" asp-action="Index"><i class="bi bi-basket"></i> Basket</a>
                            </div>
                        </li>
                    </ul>
                   <partial name="_LoginPartial"/>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>